# Generated by Django 2.1.11 on 2019-11-11 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KumoGT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Exam_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('result', models.CharField(choices=[('none', '----'), ('pass', 'Pass'), ('fail', 'Fail')], default='none', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('room', models.CharField(blank=True, max_length=255)),
                ('abstract', models.CharField(blank=True, max_length=1023)),
                ('degree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KumoGT.Degree')),
            ],
        ),
        migrations.CreateModel(
            name='Pre_Exam_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Prelim Date')),
                ('result', models.CharField(choices=[('none', '----'), ('pass', 'Pass'), ('fail', 'Fail')], default='none', max_length=255)),
                ('degree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KumoGT.Degree')),
            ],
        ),
        migrations.CreateModel(
            name='T_D_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField()),
                ('degree', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KumoGT.Degree')),
            ],
        ),
        migrations.AlterField(
            model_name='deg_plan_doc',
            name='doc_type',
            field=models.CharField(choices=[('not sel', 'Not Selected'), ('deg plan', 'Degree Plan'), ('P. change commitee', 'Petition for change of committee'), ('P. course change', 'Petition for course change'), ('P. extension of time limits', 'Petition for extension of time limits'), ('P. waivers of exceptions', 'Petition for waivers of exceptions'), ('mdd', 'MDD'), ('other', 'Other')], default='not sel', max_length=255),
        ),
    ]
