# Generated by Django 2.2.6 on 2019-10-28 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KumoGT', '0002_document_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deg_Plan_Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appr_cs_date', models.DateField()),
                ('appr_ogs_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=511)),
                ('doc_type', models.CharField(choices=[('not sel', 'Not Selected'), ('deg plan', 'Degree Plan'), ('other', 'Other')], default='not sel', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fin_Exam_Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appr_cs_date', models.DateField()),
                ('appr_ogs_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=511)),
                ('doc_type', models.CharField(choices=[('not sel', 'Not Selected'), ('request', 'Request for Final Examination'), ('req for exemp', 'Request for exemption from Final Examination'), ('report', 'Report of Final Exam')], default='not sel', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pre_Exam_Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appr_cs_date', models.DateField()),
                ('appr_ogs_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=511)),
                ('doc_type', models.CharField(choices=[('not sel', 'Not Selected'), ('checklist', 'Preliminary Exam Checklist'), ('report', 'Preliminary Exam Report'), ('written', 'Preliminary Exam Written')], default='not sel', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('uin', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('not seleted', 'Not Selected'), ('male', 'Male'), ('female', 'Female')], default='not sel', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='T_D_Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appr_cs_date', models.DateField()),
                ('appr_ogs_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=511)),
                ('doc_type', models.CharField(choices=[('not sel', 'Not Selected'), ('approval', 'Thesis/Dissertation Approval Page'), ('t_d', 'Thesis/Dissertation')], default='not sel', max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KumoGT.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='T_D_Prop_Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appr_cs_date', models.DateField()),
                ('appr_ogs_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=511)),
                ('doc_type', models.CharField(choices=[('not sel', 'Not Selected'), ('title page', 'Thesis/Dissertation Proposal Title Page'), ('prop', 'Thesis/Dissertation Proposal')], default='not sel', max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KumoGT.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='pre_exam_doc',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KumoGT.Student'),
        ),
        migrations.AddField(
            model_name='fin_exam_doc',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KumoGT.Student'),
        ),
        migrations.AddField(
            model_name='deg_plan_doc',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KumoGT.Student'),
        ),
    ]
