# Generated by Django 2.2.6 on 2019-10-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KumoGT', '0003_auto_20191027_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deg_plan_doc',
            name='appr_cs_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deg_plan_doc',
            name='appr_ogs_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fin_exam_doc',
            name='appr_cs_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fin_exam_doc',
            name='appr_ogs_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pre_exam_doc',
            name='appr_cs_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pre_exam_doc',
            name='appr_ogs_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='t_d_doc',
            name='appr_cs_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='t_d_doc',
            name='appr_ogs_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='t_d_prop_doc',
            name='appr_cs_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='t_d_prop_doc',
            name='appr_ogs_date',
            field=models.DateField(null=True),
        ),
    ]
